import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import { useEffect, useRef, useState } from 'react'
import logo from '../public/Espresso-1.png'
import '../styles/Home.module.css'
import NewsItem from '../components/NewsItem'
import {useTheme} from 'next-themes'
import axios from 'axios'
import Footer from '../components/Footer'
import { useRouter } from 'next/router'

export default function Home() { 
  const axios=require("axios")
  const [articles,setArticles]=useState([])
  const [loading,setLoading]=useState(true)
  const {theme,setTheme}=useTheme()
  // const updateNews=async()=> {  
  //   const url = `https://newsapi.org/v2/top-headlines?country=in&apiKey=044490d459c5491ab681ca7a4b0283b9`
  //   setLoading(true)
  //   let data = await fetch(url)   
  //   let parsedData = await data.json()
  //   setArticles(parsedData.articles)
  //   setLoading(false)
  // }
  const options = {
    method: 'GET',
    url: 'https://bing-news-search1.p.rapidapi.com/news',
    params: {safeSearch: 'Off', textFormat: 'Raw'},
    headers: {
      'X-BingApis-SDK': 'true',
      'X-RapidAPI-Key': '4c71af7278msh39f46b72048b825p11d8bdjsn89cf675bd909',
      'X-RapidAPI-Host': 'bing-news-search1.p.rapidapi.com'
    }
  };
  
  axios.request(options).then(function (response) {
    console.log(response.data);
    setArticles(response.data.value)
    console.log(articles)
  }).catch(function (error) {
    console.error(error);
  });
  // useEffect(()=>{
  //   updateNews();
  //  },[])
  const router=useRouter();
  const searchInput=useRef(null);
  const search=(e)=>{
    e.preventDefault();
    const searchTerm=searchInput.current.value;
    if(!searchTerm){
      return;
    }
    router.push(`/search?term=${searchTerm}`)
  }
  return (
    <>
      <Head>
        <title>Espresso</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
        <script src="https://kit.fontawesome.com/0ac391dae9.js" crossorigin="anonymous" async></script>
      </Head>
      {/* Navbar */}
      <header className='flex justify-around items-center py-5 sm:px-2'>
        <div className='flex space-x-5 ml-1 sm:ml-3'>
        <p className='link text-sm dark:text-white'>About</p>
        <p className='link text-sm dark:text-white'>Store</p>

        <span className="material-symbols-outlined link hover:text-decoration-line:none dark:text-white" onClick={() => {if(theme==="light"){setTheme('dark')} else{setTheme('light')}}}>
{theme==="light"?"light_mode":"dark_mode"}
</span>
        </div>
        <Avatar url="https://parade.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cq_auto:good%2Cw_1200/MTkwNTgxMDkwMDk3NTcxNzA4/taylor-swift-removebg-1.png"/>
        <div className='flex space-x-5 mr-1 sm:ml-3'>
        <p className='link text-sm dark:text-white'>Mail</p>
        <p className='link text-sm dark:text-white'>Images</p>
        <span className="material-symbols-outlined link hover:text-decoration-line:none dark:text-white">
grid_view
</span>
        </div>
      </header>
      {/* main */}
      <form className='flex flex-col items-center mt-24 flex-grow mx-2' onSubmit={search}>
      <Image src={logo} height={120} width={300}/>
      <div className='flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md border rounded-full px-5  border-gray-200 items-center sm:max-w-xl lg:max-w-2xl'>
      <span className="material-symbols-outlined text-gray-600">
    search
    </span>
    <input type="text" className='flex-grow no-outline focus:ring-0 focus:border-none border-none focus:outline-none bg-transparent' ref={searchInput}/>
    <span class="material-symbols-outlined cursor-pointer text-gray-600 hover:text-indigo-500 focus:text-indigo-500">
mic
</span>
</div>
      </form>
      <h1 className="text-center mt-10 font-semibold text-4xl text-green-600 my-5 mb-10 dark:text-indigo-300">Latest News</h1>
      <div className='flex items-center justify-center w-full'>
      <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-4 w-full mb-5 mx-2'>
      {articles.map((element,index) => {
              return <NewsItem key={index} title={element.name} description={element.description}
              imageUrl={element.provider[0].image.thumbnail.contentUrl} newsUrl={element.url} author={element.author} date={element.datePublished}
              source={element.provider[0].name}/>
            })}
      </div>
      </div>
      <Footer/>
      </>
  )
}
